eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/,http://admin:admin@localhost:8763/eureka/
  instance:
    hostname: localhost

server:
  port: 8092

spring:
  application:
    name: seviveProductTwo