spring:
  profiles:
    active: dev2 #当前激活的配置文件
  application:
    name: Eureka-Server

dev:
  host: localhost
  dev1Port: 8761
  dev2Port: 8762
  dev3Port: 8763

#server:
#  port: 8761

##SpringSecurity实现身份认证配置。在WebSecurityConfig中和设置Eureka的地址占位符使用
#loginname: admin
#password: 1111


# 安全认证的配置
#security:
#  basic:
#    enabled:true
#    #enabled: true
#    user:
#      name: admin  # 用户名
#      password: 1111   # 用户密码

#eureka:
 # instance:
#    hostname: localhost
#  client:
#    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
#    registerWithEureka: false
#    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
